name: Build LaTeX

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/xu-cheng/texlive-full:latest
      
    steps:
      - uses: actions/checkout@v5

      - name: Compile
        run: make all

      - name: Upload Rulebook
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Rulebook
          path: build/Rulebook.pdf

      - name: Upload Local_chair_instructions
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: instructions
          path: build/Local_chair_instructions.pdf
